export const CONST_RPC_ERROR_CODE_PARSE_ERROR = -32700;
export const CONST_RPC_ERROR_CODE_INVALID_REQUEST = -32600;
export const CONST_RPC_ERROR_CODE_METHOD_NOT_FOUND = -32601;
export const CONST_RPC_ERROR_CODE_INVALID_PARAMS = -32602;
export const CONST_RPC_ERROR_CODE_INTERNAL_ERROR = -32603;
export const CONST_RPC_ERROR_CODE_SERVER_ERROR = -32000;
